//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancellation_Data
    {
        public int Canc_ID { get; set; }
        public Nullable<int> Book_ID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Train_no { get; set; }
        public Nullable<System.DateTime> Canc_Date { get; set; }
        public Nullable<int> No_tickets_Canc { get; set; }
        public Nullable<int> Refund_Amount { get; set; }
    
        public virtual Booking_Data Booking_Data { get; set; }
    }
}
