//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Train()
        {
            this.Booking_Data = new HashSet<Booking_Data>();
        }
    
        public int Train_no { get; set; }
        public string Train_name { get; set; }
        public string Class { get; set; }
        public Nullable<int> Total_Berths { get; set; }
        public Nullable<int> Available_Berths { get; set; }
        public string Source_loc { get; set; }
        public string Destination { get; set; }
        public Nullable<System.DateTime> Date_of_Travel { get; set; }
        public Nullable<int> Fare { get; set; }
        public string Train_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_Data> Booking_Data { get; set; }
    }
}
